"""Stable logical names for generated reference-selector hierarchy."""

VREF_SWITCH_INSTANCE_NAME = "VREF_TG"
VSS_SWITCH_INSTANCE_NAME = "VSS_TG"

VREF_NET_NAME = "VREF"
VSS_NET_NAME = "VSS"
COMMON_NET_NAME = "COMMON"
SELECT_NET_NAME = "SELECT"
SELECT_BAR_NET_NAME = "SELECT_BAR"

__all__ = [
    "VREF_SWITCH_INSTANCE_NAME",
    "VSS_SWITCH_INSTANCE_NAME",
    "VREF_NET_NAME",
    "VSS_NET_NAME",
    "COMMON_NET_NAME",
    "SELECT_NET_NAME",
    "SELECT_BAR_NET_NAME",
]
